# サイト基本情報
title: "Jekyll_Practice"
description: "Jekyllの練習用(mikann-260作)"
lang: ja

# URL設定
url: "https://mikann-260.github.io"
baseurl: "/Jekyll_Practice"

# 作成者
author: mikann-260

# ビルド設定
source: docs

# プラグイン
plugins:
  - jekyll-sitemap
